.SH SAMPLE SECTION 
The SH macro starts a section, boldfacing the section title. 
.P 
The P request starts a new paragraph. The I request sets its argument in 
.I italics. 
.IP * 
This starts an indented paragraph with an asterisk label. More text for the first bulleted paragraph. 
.TP 
This first line will become a paragraph label This will be the first line in the paragraph, further indented relative to the label.
The blank line just above this is treated almost exactly like a paragraph break (actually, like the troff-level request .sp 1). 
.SS A subsection 
This is subsection text.
