# EMSCRIPTEN TUTORIAL: WEB ASSEMBLY

# install: get repo
git clone https://github.com/emscripten-core/emsdk.git

# install: go to folder
cd emsdk

# install: download and install the latest SDK tools.
./emsdk install latest

# make the "latest" SDK "active" for the current user. (writes ~/.emscripten file)
./emsdk activate latest

# activate PATH and other environment variables in the current terminal
source ./emsdk_env.sh

# verify emscripten installation
emcc -v

# To build the JavaScript version of a C code, simply specify the
# C/C++ file after emcc (use em++ to force compilation as C++):

emcc hello_world.c

# You should see two files generated by that command: a.out.js and
# a.out.wasm. The second is a WebAssembly file containing the
# compiled code, and the first is a JavaScript file containing the
# runtime support to load and execute it. You can run them using
# node.js:

node a.out.js

# This prints “hello, world!” to the console, as expected.

# Emscripten can also generate HTML for testing embedded
# JavaScript. To generate HTML, use the -o (output) command and
# specify an html file as the target file:

./emcc tests/hello_world.c -o hello.html

# you can now open hello.html in a web browser.

https://emscripten.org/docs/getting_started/Tutorial.html#tutorial
